"use client";
import { useMemo, useState } from "react";
import { EmptyState } from "./EmptyState";

export type Column<T> = { header: string; accessor: keyof T | ((row: T) => React.ReactNode); className?: string };
export function DataTable<T extends { id?: string }>({ data, columns, actions, searchPlaceholder="Search...", pageSize=10 }: { data:T[]; columns:Column<T>[]; actions?:(row:T)=>React.ReactNode; searchPlaceholder?:string; pageSize?:number }) {
 const [q,setQ]=useState(""); const [page,setPage]=useState(1);
 const filtered=useMemo(()=>data.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[data,q]);
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize)); const rows=filtered.slice((page-1)*pageSize,page*pageSize);
 return <div className="space-y-4"><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder={searchPlaceholder} className="w-full rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm outline-none ring-emerald-700 focus:ring-2"/>{rows.length===0?<EmptyState title="No matching records" description="Try another search or add a new record."/>:<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200 text-sm"><thead className="bg-slate-50"><tr>{columns.map((c,i)=><th key={i} className={`px-4 py-3 text-left font-semibold text-slate-600 ${c.className??""}`}>{c.header}</th>)}{actions&&<th className="px-4 py-3 text-right font-semibold text-slate-600">Actions</th>}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row,idx)=><tr key={row.id??idx} className="hover:bg-slate-50">{columns.map((c,i)=><td key={i} className={`px-4 py-3 text-slate-700 ${c.className??""}`}>{typeof c.accessor==="function"?c.accessor(row):String(row[c.accessor]??"—")}</td>)}{actions&&<td className="px-4 py-3 text-right">{actions(row)}</td>}</tr>)}</tbody></table></div></div>}<div className="flex items-center justify-between text-sm text-slate-500"><span>{filtered.length} record(s)</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">Prev</button><span className="px-2 py-1">{page}/{pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">Next</button></div></div></div>
}
